### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by ZatchBell68** [YunoHost-Apps/phpboost_ynh#1]
Bonjour

J'ai une erreur 403 après installation,

ci-joint une partie de mon log

```
019/02/13 20:07:42 [error] 4795#4795: *174 directory index of "/var/www/phpboost/" is forbidden, client: 192.168.0.254, server: sos-info68.ovh, request: "GET /phpb/ HTTP/2.0", host: "sos-info68.ovh"
2019/02/13 20:10:01 [error] 4795#4795: *174 directory index of "/var/www/phpboost/" is forbidden, client: 192.168.0.254, server: sos-info68.ovh, request: "GET /phpb/ HTTP/2.0", host: "sos-info68.ovh"
```

**Comment by liberodark** [comment]
c'est écrit NOT WORK IS IN DEV c'est normal comme erreur.
Pour l'instant je cherche comment le finir mais c'est pas facile ce site serait un des plus dur à mettre sur nginx.

**Comment by ZatchBell68** [comment]
Désolé je n'avais pas vu. Effectivement il n'est vraiment pas prévu pour nginx, il y a des règles de rewrite sur le wiki mais c'est pour les anciennes version.
